### ISSUE TITLE
enable travis

### ISSUE THREAD

**Issue by jorgheymans** [source-foundry/java-glyph-tester#4]
@chrissimpkins could you enable travis ci for this repo ? Should be just a toggle in the repo configuration somewhere : https://travis-ci.org/getting_started

**Comment by chrissimpkins** [comment]
Done.  Should be all set.

https://travis-ci.org/source-foundry/java-glyph-tester

**Comment by chrissimpkins** [comment]
Let me know if the current settings do not work

**Comment by chrissimpkins** [comment]
👍 [![Build Status](https://travis-ci.org/source-foundry/java-glyph-tester.svg?branch=master)](https://travis-ci.org/source-foundry/java-glyph-tester)

**Comment by jorgheymans** [comment]
awesome thanks 👍

**Comment by chrissimpkins** [comment]
@jorgheymans : Added Codecov coverage access if you are interested in it for your CI testing:

https://codecov.io/gh/source-foundry/java-glyph-tester
