### ISSUE TITLE
allow for glyph repetition

### ISSUE THREAD

**Issue by jorgheymans** [source-foundry/java-glyph-tester#7]
As per David's comment:

Additionally, and I think this needs to be ​_emphasized_​ (and @chris might be able to provide some additional insight into this): I don't think rendering a single glyph is good enough. I think we need to render perhaps 4 or 5 of the same glyph horizontally next to each other. Not as separate glyphs at separate horizontal positions, but as if they're a single word. The reason for this is that fractional width of the glyph-box I mentioned earlier. I don't know about other platforms, but I've noticed on Mac OS X that the subpixel anti-aliasing of certain glyphs differs depending on the horizontal position it's drawn at.

**Comment by burodepeper** [comment]
To illustrate this:

![schermafbeelding 2016-05-18 om 07 11 39](https://cloud.githubusercontent.com/assets/3703530/15348200/ea694fbc-1cc8-11e6-8529-9d053100bb27.png)

**Comment by jorgheymans** [comment]
--repeatGlyph parameter added
